#!/bin/sh
set -e

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d jetty9 remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


# Remove cached files
rm -rf /var/cache/jetty9/*

case "$1" in
    remove)
        # Remove ROOT webapp if not modified
        RWLOC="/var/lib/jetty9/webapps/root"
        RWFILES="$RWLOC/index.html $RWLOC/jetty_banner.gif"
        if [ "`(cat $RWFILES | md5sum -) 2>/dev/null | cut -d ' ' -f 1`" \
                            = "12471c4b3020defb7ebd30ef84c0f9dd" ] ; then
            rm $RWFILES
            rmdir --ignore-fail-on-non-empty \
                /var/lib/jetty9/webapps/root \
                /var/lib/jetty9/webapps \
                /var/lib/jetty9 || true
        fi
        if [ -d "/var/cache/jetty9" ] ; then
            rm -rf /var/cache/jetty9
        fi
    ;;

    purge)
        # Remove user/group and log files (don't remove everything under
        # /var/lib/jetty because there might be user-installed webapps)
        deluser jetty || true
        rm -rf /var/log/jetty9
        if [ -d "/var/lib/jetty9" ] ; then
            rmdir --ignore-fail-on-non-empty /var/lib/jetty9 || true
        fi
        rmdir --ignore-fail-on-non-empty /etc/jetty9/contexts /etc/jetty9 || true

        # clean up /etc/authbind after conffiles have been removed
        rmdir --ignore-fail-on-non-empty /etc/authbind/byuid /etc/authbind || true
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Nothing to do here
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
